### ISSUE TITLE
incorrect file path for leaflet.draw

### ISSUE THREAD

**Issue by skorasaurus** [enam/neighborhoods#2]
Hi, 
awesome tool; thank you again for making it. 

A really minor error: 
the file path mentioned for leaflet.draw index.html is lowercase; but the file is stored in the repo as Leaflet.draw.  (https://github.com/enam/neighborhoods/blob/master/index.html#L16)

**Comment by PhillipBost** [comment]
Awesome catch. Thank you!

Phil

**Comment by PhillipBost** [comment]
Oh wow, I'm a dummy. I thought this message was for _my_ map project, not
enam's.
Sorry for replying and causing confusion, everyone.

**Comment by enam** [comment]
Good catch, thanks @skorasaurus.
